In [76]:
import numpy as np
import copy

In [77]:
# X = [[1, 3, 2, 5, 7], [100, 320, 250, 520, 800], [3, 9, 6, 9, 25]]
X_in =[[1, 100, 3], 
    [3, 320, 9],
    [2, 250, 6],
    [5, 520, 9],
    [7, 800, 25]]
y_in = [2.5, 6.2, 4, 10, 15]
w_in = [0, 0, 0]
b_in = 0

In [78]:

X = np.array(X_in)
y = np.array(y_in)
w = copy.deepcopy(w_in)
b = b_in
X.shape, y.shape

((5, 3), (5,))

In [79]:
n_rows = X.shape[0]
n_cols = X.shape[1]
n_rows, n_cols

(5, 3)

In [80]:
def compute_cost(X_mat, y_vec, w_vec, b_sca, m):
    return 1/2*m * sum( ((np.matmul(X_mat, w_vec) + b_sca) - y_vec) ** 2)

# Sample cost
compute_cost(X, y, np.ones(3), np.zeros(5), n_rows)

2807572.2250000006

In [89]:
np.transpose(X)[1]

array([100, 320, 250, 520, 800])

In [100]:
def compute_gradient(X_mat, w_vec, b_sca, m):
    
    dj_dw = sum([1/m * (np.matmul(X_mat, w_vec) + b_sca) * np.transpose(X)[i] for i in range(len(w_vec))])
    dj_db = 1/m * np.matmul(X_mat, w_vec) + b_sca 
    return (dj_dw, dj_db)


In [101]:
compute_gradient(X, np.ones(3), b, n_rows)

(array([  2163.2,  22044.8,  13312.8,  57031.2, 138444.8]),
 array([ 20.8,  66.4,  51.6, 106.8, 166.4]))

In [102]:
def gradient_descent(iters, alpha=.001):
    
    X = np.array(X_in)
    y = np.array(y_in)
    w = copy.deepcopy(w_in)
    b = b_in
    X.shape, y.shape

    for i in range(iters):
        (dj_dw, dj_db) = compute_gradient(X, w, b, n_rows)
        w = w - (alpha * dj_dw)
        b = b - (alpha * dj_db)
        if i % 500 == 0:
            cost = compute_cost(X, y, w, b, n_rows)
            print(f"w : {w}, b: {b} , cost: {cost}")
            

In [103]:
gradient_descent(10000)

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [33]:
w = np.array(w)
X.shape, w.shape
w = np.ones(3)
w

array([1., 1., 1.])

In [34]:
X

array([[  1, 100,   3],
       [  3, 320,   9],
       [  2, 250,   6],
       [  5, 520,   9],
       [  7, 800,  25]])

In [45]:
# np.matmul(X, np.transpose(w)) + b
np.matmul(X,w) + b

array([104., 332., 258., 534., 832.])

array([104., 332., 258., 534., 832.])