In [1]:
import numpy as np

In [49]:
# Vector creation (Shape as input)

a = np.zeros(4);  av = np.zeros((4,2))
print(f"a: {a}\na.shape: {a.shape}\nav: \n{av} , \nav.shape: {av.shape}\n")

o = np.ones(5)
r = np.random.random_sample((4,3))
print(f"o: {o}\nr: \n{r}, \nr.dtype: {r.dtype}")

a: [0. 0. 0. 0.]
a.shape: (4,)
av: 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] , 
av.shape: (4, 2)

o: [1. 1. 1. 1. 1.]
r: 
[[0.18928798 0.76406715 0.41735531]
 [0.60978975 0.69207517 0.44627046]
 [0.37007269 0.62363404 0.89629129]
 [0.48702337 0.82931307 0.47745877]], 
r.dtype: float64


In [51]:
# Shape NOT as input
a = np.arange(4.0, 10.0)
print(f"a: {a}, a.shape: {a.shape}, a.dtype: {a.dtype}\n")

r = np.random.rand(3)
print(f"r: {r}, r.shape: {r.shape}")

a: [4. 5. 6. 7. 8. 9.], a.shape: (6,), a.dtype: float64

r: [0.59979764 0.21829123 0.88326228], r.shape: (3,)


In [59]:
# Initialize values
a = np.array([.1, .2, .5])
print(f"a: {a}, a.shape: {a.shape}, a.dtype: {a.dtype}\n")

a = np.array([[3,4], [5,2], [2,2]])
print(f"a: \n{a}, a.shape: {a.shape}, a.dtype: {a.dtype}\n")



a: [0.1 0.2 0.5], a.shape: (3,), a.dtype: float64

a: 
[[3 4]
 [5 2]
 [2 2]], a.shape: (3, 2), a.dtype: int64



In [63]:
# Operations on Vectors
a = np.arange(10)
a[0] , a[-1]

(0, 9)

In [75]:
# Slicing

a = np.arange(10)
print(f"a = {a}")

# [start:stop:step]
m = a[2:5:1]; print(f"m = {m}")
m = a[2:5:2]; print(f"m = {m}")
m = a[2:]; print(f"m = {m}")
m = a[2::3]; print(f"m = {m}")
m = a[:5:3]; print(f"m = {m}")



a = [0 1 2 3 4 5 6 7 8 9]
m = [2 3 4]
m = [2 4]
m = [2 3 4 5 6 7 8 9]
m = [2 5 8]
m = [0 3]


In [82]:
# Single vector operations

a = np.array([1, 2, 5])

o = -a; print(f"o = {o}")
o = a ** 3; print(f"o = {o}")
o = np.sum(a); print(f"o = {o}")
o = np.mean(a); print(f"o = {o}")


o = [-1 -2 -5]
o = [  1   8 125]
o = 8
o = 2.6666666666666665


Element Wise Op: $$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$

In [95]:
b = np.power(a, 3)
a, b, a + b


array([ 4,  8, 20])

In [96]:
a * 4 

array([ 4,  8, 20])

Dot Product : $$ x = \sum_{i=0}^{n-1} a_i b_i $$


In [100]:
sum(a * b), np.dot(a,b)

(642, 642)

Matrices

In [103]:
# Creation

a = np.zeros((3, 2))
print(f"a: \n{a}")

r = np.random.random_sample((2, 3))
print(f"r: \n{r}")


a: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]
r: 
[[0.50781667 0.71665664 0.45240073]
 [0.43367065 0.76521555 0.21024209]]


In [110]:
# Vector indexing on matrices

a = np.arange(6).reshape(2, 3)
a, a.shape

(array([[0, 1, 2],
        [3, 4, 5]]),
 (2, 3))

In [114]:
# In a similar manner, The -1 argument tells the routine to compute the number of rows 
# given the size of the array and the number of columns.
a = np.arange(6).reshape(-1, 2)
a, a.shape

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 (3, 2))

In [115]:
a = np.arange(20).reshape(-1,4)
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 (5, 4))

In [116]:
a[:, 2]

array([ 2,  6, 10, 14, 18])

In [118]:
a[2, ::2]

array([ 8, 10])

In [121]:
a[:, 1:5:2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])